CREATE TABLE
    MY_EMPLOYEE (
        ID INTEGER PRIMARY KEY NOT NULL,
        LAST_NAME VARCHAR(25) NOT NULL,
        FIRST_NAME VARCHAR(25) NOT NULL,
        USERID VARCHAR(8) NOT NULL,
        SALARY NUMERIC(9,2) NOT NULL
    )
;